[general]
working_directory = "~/"
live_config_reload = true
ipc_socket = false

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
decorations = "None"
opacity = 0.8
blur = false
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"
resize_increments = true

[scrolling]
history = 1000

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 8

[colors]
selection = { text = "#41112c", background = "#934674" }
[colors.primary]
foreground = "#e18bbe"
background = "#2d1523"
[colors.normal]
black  = "#665c54" 
red  = "#d65049"
green  = "#8bb655"
yellow  = "#e78a4e"
blue  = "#5381b4"
magenta  = "#d36a9b"
cyan  = "#7d94b9"
white  = "#d4be98"
[colors.bright]
black  = "#928374"
red  = "#ea6562" 
green = "#89f13c"
yellow = "#d8ff20"
blue = "#5566ec"
magenta = "#d3399b"
cyan = "#7daeec"
white = "#f7ead3"

